[phases.setup]
nixPkgs = ['php84', 'php84Extensions.gd', 'php84Extensions.sqlite3']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-scripts',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'touch database/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'